### PR TITLE
Add `Process.joined`.

### PR DESCRIPTION
**Pull request by aloiscochard**
I found that one to be useful, let me know IRL if that's a bad idea ;-)

### CODE REVIEW

**Comment by YoEight** [comment]
We have `asParts` already :-)

```
asParts :: Foldable f => Process (f a) a
asParts = repeatedly $ await >>= traverse_ yield
```

**Comment by aloiscochard** [comment]
oh nice! thanks @YoEight

**Comment by statusfailed** [comment]
Any reason this doesn't have the below type?

    asParts :: (Monad m, Foldable f) => ProcessT m (f a) a

 I only really use the monad transformer versions of Machine/Process, so I often find myself writing this one out.

**Comment by YoEight** [comment]
```haskell
type Process a b = Machine (Is a) b
type Machine k o = forall m. Monad m => MachineT m k o
```

So the `Monad` constraint is implied

**Comment by statusfailed** [comment]
Oh great! I thought it was Identity instead of forall. Thanks!

**Pull request closed without merging**
