### PR TITLE
Use cabal-docspec

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
ping. If this slipped through.

**Comment by phadej** [comment]
@RyanGlScott is this missing something?

**Comment by treeowl** [comment]
I'll try to take a look today, but no guarantees.

**Comment by RyanGlScott** [comment]
Curiously, this one didn't make it into my inbox until your comment at https://github.com/ekmett/machines/pull/111#issuecomment-757564222. This looks good to me, however.

**Pull request merged**
