### PR TITLE
Add MooreT module

### PR DESCRIPTION
**Pull request by bens**
Any more suggestions for instances or functions would be appreciated.

### CODE REVIEW

**Comment by bens** [comment]
Bump?

**Comment by YoEight** [comment]
Sorry for the delay, I didn't see the first notification.

**Comment by YoEight** [comment]
LGTM. On a different, is it still relevant to be overly aggressive with inlining? I mean, most of the time, GHC does a great job in this regard. Your code might need some updates in a few places though, as GHC requires a function to be fully applied to be a candidate for inlining.

**Comment by bens** [comment]
Perhaps not worthwhile, I haven't looked at any core, I was more following the example of the other modules.  I'll check for partial applications, thanks.

**Pull request merged**
