### PR TITLE
Generalizations to Tee

### PR DESCRIPTION
**Pull request by alang9**

### CODE REVIEW

**Comment by HuwCampbell** [comment]
I think your version of `tee` is inside out.

Isn't the point that the tee's plan can use a different language on each side? So `Tee (Stack a) (Is c) d` can be used?

**Comment by alang9** [comment]
Right, I'm not sure what you mean by "inside out".

**Comment by HuwCampbell** [comment]
You appear to be providing ways to construct a generalised tee from a simple one, (which one could also do with a plan) but not a way to use one.

**Comment by alang9** [comment]
Ah yes, I think that's right. I think to be able to use the more generalized tee effectively requires solving #39. I posted a gist of a solution there, but it's not very elegant.

**Comment by YoEight** [comment]
So are you still interested in merging this PR ?

**Comment by alang9** [comment]
No I don't think this is so interesting unless #39 can be solved, but I'd like to hear others' opinions.

**Comment by YoEight** [comment]
Alright, so I close this PR until it gets in shape

**Comment by YoEight** [comment]
Any news on this front ?

**Comment by alang9** [comment]
Sorry I've been incredibly busy and haven't had time to look at this. I'd love for @HuwCampbell to chime in

**Comment by HuwCampbell** [comment]
Time... it gets away.

Nonetheless, I would probably not go with merging this as it stands.

First it breaks backwards compatibility. But excluding that:  `TG` may well be actually prove a good encoding, but the `tee` function seems inverted (as the requirement of an internal `Refl` in it shows, it shouldn't hold any preconceptions of its internals). If tees are to be composable, then their drivers need to be too.

Hypothetically, as I haven't really nutted this out, one might pass `<~` and `stack` to a new `tee` function to drive a `TG (Is a) (Stack b)`, which then makes a `TG (Is a) (Is b)`. They may then cap it with two sources to make a new source. But the stack push and pop commands are expressed inside the plan `GT`, so one is able to express more.

A nested tee within a tee might then be possible by passing the `tee` driver to one side. So one could in effect source from 4 sources at once.

**Comment by YoEight** [comment]
I close this PR for now then. Thanks for your input

**Comment by gelisam** [comment]
Looks like this PR is trying to generalize `T` so that it can be nested in order to describe a machine with more than 2 inputs. Have you considered generalizing from `T (a :: *) (b :: *) (i :: *)` to `Elem :: (as :: [*]) (i :: *)`, thus enumerating the inputs in a list instead of in a binary tree?

'cause I just wrote a Machine which uses that :)

https://gist.github.com/gelisam/a8bee217410b74f030c21f782de23d11

**Pull request closed without merging**
