### PR TITLE
Implement ZipWith

### PR DESCRIPTION
**Pull request by YoEight**
```haskell
runT $ zipWith (+) (source [1,3,5,7,9]) (source [0,2,4,6,8])
-- [1,5,9,13,17]
```

### CODE REVIEW

**Comment by ekmett** [comment]
I'm going through and doing some cleanup.

What do we need to do to get this back to a buildable state and merge it?

I'd like to turn the _zipWith combinator into the thing that we export though, since the other is a trivial composition.

**Comment by YoEight** [comment]
Why do you think about the naming, I mean `teeOutput` and to some extent how would you name `_zipWith` ?

**Comment by ekmett** [comment]
Maybe just renaming `_zipWith` as `zipWith`, and `teeOutput` as `teeT`?

**Comment by YoEight** [comment]
Ok but what about the one that is already named `zipWith` ?

**Comment by ekmett** [comment]
It is just a trivial composition of the more primitive `teeT` and
`zipWith`.

I'd say it fails to hit the Fairbairn threshold and drop it.

**Pull request merged**
