### PR TITLE
Implement bidirectional communication between two MachineT.

### PR DESCRIPTION
**Pull request by YoEight**
```haskell
import Control.Monad.Trans

data Req
    = Ping
    | ReadLn String
 
data Resp
    = Started
    | Pong
    | String String 

server :: Proxy a' a Req Resp IO r
server = construct $ do
    liftIO $ putStrLn "Bootstrapping server..."
    req <- respond Started
    loop req
  where
    loop Ping = do
        liftIO $ putStrLn "Get a Ping"
        respond Pong >>= loop
    loop (ReadLn src) = do
        l <- liftIO $ do
                  putStr $ "Read from " ++ src ++ " > "
                  getLine
        respond (String l) >>= loop
 
client :: Proxy Req Resp b' b IO r
client = construct $ do
    Pong <- request Ping
    liftIO $ putStrLn "Receive PONG"
    String s <- request (ReadLn "terminal")
    liftIO $ putStrLn $ "Got message: " ++ s 

main :: IO ()
main = runEffect_ (server >>~ (const client)) 
```
The output

```
Bootstrapping server...
Get a Ping
Receive PONG
Read from terminal > hello world
Got message: hello world 
```

### CODE REVIEW

**Comment by cartazio** [comment]
looks pretty good (at least from a shallow skim).

**Comment by aloiscochard** [comment]
Ceci n'est pas une pipe? (sorry)

I'll give it a try, I have a few place where I can use it!

**Comment by YoEight** [comment]
@bitemyapp suggested I change `Proxy` nomenclature. I was about to do it and finally change my mind. The reason was because `base` has `Data.Proxy` module with `Proxy` data constructor, resulting to possible name conflict. 

After some thinking, I prefer to keep it that way because it's more familiar (regarding `pipes` library). Moreover, name conflict shouldn't happen because `Data.Proxy` and `machines` target different problem spaces.

**Comment by YoEight** [comment]
I no longer re-export `Data.Machine.Pipe` in `Data.Machine` because it could lead to name conflict with `Data.Machine.Stack`, on `push` function.

**Comment by ekmett** [comment]
I have to admit I never really liked the Pipes vocabulary around Proxy, and for that matter, we've deliberately avoided the Pipe metaphor in the package to date.

**Comment by ekmett** [comment]
Not sure what color to put on the bikeshed, just giving a general sense that there is some disquiet.

**Comment by cartazio** [comment]
i too kinda agree that the `Proxy` metaphor in pipes is a bit confusing, or at the very least isn't ideal

**Comment by bitemyapp** [comment]
Conversation on Twitter suggested the type alias be renamed `Pipe`, the datatype be renamed Mailbox or something similar.

I also don't care for how Pipes organizes things. Regret the bikeshedding, but it did make Pipes harder to understand.

**Comment by cartazio** [comment]
is MailBox quite the right  term? I mean... you dont usually compose local mailboxes right? you just have one locally, right? I realize i'm pouring the paint by quibbling here :)

**Comment by cartazio** [comment]
that reminds me, Gabriel has explicitly said that if he didn't care about backwards compat, he'd have named `Proxy` `Pipe` to begin with

**Comment by cartazio** [comment]
that reminds me, Gabriel has explicitly said that if he didn't care about backwards compat, he'd have named `Proxy` as `Pipe` to begin with. And in this context we dont have any backwards compat to care about!

**Comment by acowley** [comment]
There are two pieces here, the data type that mediates messages between upstream and downstream, and the sequence of interactions with that data type. The `Mailbox` suggestion that I had made among several others on IRC was for that data type, while the stream itself (an application of `MachineT`) would have a different name.

Composition is done with that steam type synonym. I think the lack of that distinction is part of what makes the `Proxy` name in pipes so distasteful to many of us.

**Comment by YoEight** [comment]
It isn't engraved on stone neither. I thought it was a problem related to name conflict. I keen to change the name (for real this time).

I want to bring to your attention that `Pipe` either means `Smoking pipe` or an `oral sex act` in French. That's why I don't say it French during conferences.

Let me know the nomenclature of your preference.

**Comment by cartazio** [comment]
Conduit!? :)

**Comment by cartazio** [comment]
hrm, but as mentioned before, pipe is a problematic name for other reasons. What about `Bus` or `Conduit` or `Trolley` or `Train` or `Subway` or `Tram`

**Comment by cartazio** [comment]
heck, why not `Highway` or `Interstate`

**Comment by bitemyapp** [comment]
magrittepipe

(Conduit is actually a good name IMO, but they're not bi-di which may mislead)

**Comment by acowley** [comment]
How about something that plays to the bidirectional aspect? We already have `Process` for simple plumbing.

**Comment by cartazio** [comment]
Elevator?

**Comment by aloiscochard** [comment]
What about `Duplex`?

http://en.wikipedia.org/wiki/Duplex_%28telecommunications%29

**Comment by YoEight** [comment]
I like `Duplex`

**Comment by acowley** [comment]
I like `Duplex`, too. Great suggestion!

**Comment by cartazio** [comment]
Is it full duplex or only half duplex?  I think full duplex requires
concurrency machinery.

**Comment by cartazio** [comment]
But yeah, I like the idea of Duplex, with just the half shed that we dont
have a full duplex :)

**Comment by bitemyapp** [comment]
(Half) Duplex seems good to me :)

**Comment by acowley** [comment]
@cartazio's right, but let's just save the name `FullDuplex` for the eventual concurrent version. `HalfDuplex` might make people think they're only getting a partial solution to their bidirectional streaming problems.

**Comment by ekmett** [comment]
Duplex or Protocol seems to capture the intuition for what it is we talk about between two machines.

Now the next concern I have is that this basically turns machines into pipes.

For me the role of machines is that it explores how to get 'what we need' out of  pipes or conduits _without_ adopting these 5 argument unmotivated data types.

**Comment by ekmett** [comment]
It isn't surprising to me that a complex API can capture this usage pattern. 

What I want is a simple one, which I can motivate.

**Comment by YoEight** [comment]
So it seems we agreed on `Duplex`

> For me the role of machines is that it explores how to get 'what we need' out of pipes or conduits without adopting these 5 argument unmotivated data types.

@ekmett I think I'm able to drop 2 type arguments. 5 types arguments are needed if you want to implement push and pull based streaming.

**Comment by ekmett** [comment]
My main concern is whether this belongs here in the main package.

**Comment by YoEight** [comment]
I admit I'm failing to understand why. It doesn't bring any new dependency and it's very similar to `Stack` in this regard. That's being said, I'm very keen to make a new package if you ask me to do so.

**Comment by treeowl** [comment]
@ekmett, my reading of it was that it's a demonstration that `machines` really is powerful enough to capture everything. I definitely support the suggestion that everything be renamed.

**Comment by ekmett** [comment]
Okay. I apparently misread the code. For some reason I had thought it was a completely separate type rather than just an input language. My objection is dropped. We can play with the names later.

**Pull request merged**
