### PR TITLE
teeT: Don't run actions too many times

### PR DESCRIPTION
**Pull request by alang9**
I think this fixes a bug in `teeT`. I also added a doctest for it, but it's a bit convoluted. Maybe there's a better test.

### CODE REVIEW

**Comment by YoEight** [comment]
Now the checks are passing, are you still interested into merging this patch ? If yes, could you squash the commits. Otherwise, I will close this ticket.

Sorry for the delay.

**Comment by acowley** [comment]
The changes to `Tee.hs` look valuable, so we should try to sort things out to get this merged.

**Comment by alang9** [comment]
Yea I think it should still be merged. Squashed the commits.

**Comment by YoEight** [comment]
Is there a reason for `.travis.yml` file to be changed ?

**Comment by alang9** [comment]
I thought travis needed this change to run the tests, but I'll revert it if it's not necessary

**Comment by YoEight** [comment]
It seems those test libraries, related to your newly introduced 'properties' test-suite, don't build on GHC 8.0.2, could you have a look on it please ?

```
QuickCheck >=2.4,
directory >=1.0 && <1.3,
doctest >=0.8 && <0.12,
filepath >=1.3 && <1.5,
test-framework-quickcheck2 >=0.2,
test-framework-th >=0.2
```

Thanks

**Comment by YoEight** [comment]
Did you have a chance to look into this ?

**Comment by alang9** [comment]
I haven't had time to figure out why the test doesn't compile, but I think this should be merged even without the test. The current behaviour is buggy

**Pull request closed without merging**
