### PR TITLE
Added instance Distributive (Moore a)

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by ekmett** [comment]
Interesting. This is effectively using it as a representable functor, represented by a list of inputs.

**Comment by mitchellwrosen** [comment]
Interesting? I stole the idea and implementation from _[your](https://hackage.haskell.org/package/free-4.12.1/docs/Control-Comonad-Cofree.html)_ comment about `Cofree`! :)

**Comment by acowley** [comment]
This is how @ekmett compliments himself.

**Comment by ekmett** [comment]
Amusingly, I realized after the fact that I'd already written the more general statement elsewhere. I just hadn't really considered the consequences here.

Note: Mealy is _also_ distributive (it is represented by a `NonEmpty a`).

**Comment by ekmett** [comment]
(and both should be instances of the profunctor equivalents as well)

**Comment by mitchellwrosen** [comment]
For the categorically uninclined who happen upon this ticket, can you clarify what you mean by 

> using Moore as a representable functor, represented by a list of inputs

My understanding is you're saying there's an isomorphism

```haskell
to :: Moore a b -> ([a] -> b)
to (Moore b _) [] = b
to (Moore _ f) (x:xs) = to (f x) xs

from :: ([a] -> b) -> Moore a b
from f = Moore (f []) (\a -> from (\as -> f (a:as)))
```

but I don't see what it has to do with this `Distributive` instance.

**Comment by ekmett** [comment]
The short version is this: Every distributive functor is representable, `Distributive` is constrained by Haskell 98 though to not actually tell you what the representation is.

**Comment by treeowl** [comment]
Can this be made an instance of Representable?

**Comment by ekmett** [comment]
Since this pull request I've already gone ahead and done so in HEAD.

**Pull request merged**
