### PR TITLE
Add functions for running machines on transformed monads.

### PR DESCRIPTION
**Pull request by treeowl**

### CODE REVIEW

**Comment by YoEight** [comment]
:+1:

**Comment by ocharles** [comment]
Looks like this would benefit from a `mapMachineT :: (forall a. m a -> n a) -> MachineT m k o -> MachineT m k o`

**Comment by treeowl** [comment]
@ocharles, we have `fitM`, which is sufficient for readers, but I don't see a way to write/use something of that type that will work for state or exceptions.

**Comment by ocharles** [comment]
Fair enough, just a passing comment :)

**Comment by ekmett** [comment]
`fitM = mapMachineT`. The latter may have been a better name. Oh well, hindsight.

**Pull request merged**
